### ISSUE TITLE
ValueError: could not convert string to float: 'Valence'

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [RiTUAL-UH/Font_LDL_2020#12]
`ValueError: could not convert string to float: 'Valence'` error when running `python3 main.py`. Any idea what is the issue?

Full error:

```
root@0c90ffaa2958:/Font_LDL_2020/Font_LDL# PYTHONIOENCODING=utf8 python3 main.py
[LOG] running on CPU
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /Font_LDL_2020/Font_LDL/logger.py:15: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

Running on CPU
[LOG] running . . . bert_seq_classification_V1
***********************printing status*************************
Train dataset: 916
Dev dataset: 131
Test dataset: 262
Train dataset words: ['We may encounter many defeats but we must not be defeated.', '• 1000+ high qualitypatterns • 9 new social sizes']
Train dataset labeles: [[0.195, 0.0, 0.12, 0.173, 0.068, 0.113, 0.045, 0.0, 0.14300000000000002, 0.14300000000000002], [0.075, 0.12, 0.241, 0.068, 0.045, 0.113, 0.14300000000000002, 0.12, 0.0, 0.075]]
Train dataset emojifeats: [array([-1.2710791e-02,  9.7703775e-03, -2.8587232e-05, ...,
       -9.4925361e-03, -1.9361263e-02,  5.0162524e-03], dtype=float32), array([ 0.00183615, -0.00894303,  0.        , ..., -0.03217574,
       -0.01422946,  0.03710809], dtype=float32)]
[LOG] num_of_unique_words:  3234
[LOG] Word embedding stats -> Perfect match: 1273; Case match: 1845; No match: 116
[LOG] num_of_unique_words:  3234
[LOG] ** EMOTION seen words: 1778, emotion_seen_stemed_dict: 246, emotion in Wnet:194  emotion NOT seen words: 1016
[LOG] num_of_unique_words:  3234
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    encoder = Encoder.get_encoder(corpus, emb_path, encoder_pkl_path=encoder_pkl)
  File "/Font_LDL_2020/Font_LDL/data.py", line 73, in get_encoder
    encoder = Encoder(corpus, emb_path)
  File "/Font_LDL_2020/Font_LDL/data.py", line 34, in __init__
    self.word2VAD, self.VAD_lst = self.get_VAD_dict(config.VAD_path, corpus.get_word_vocab())
  File "/Font_LDL_2020/Font_LDL/data.py", line 233, in get_VAD_dict
    word, valence, arosal, dominance = line.split("\t")[0], float(line.split("\t")[1]), float(line.split("\t")[2]), float(line.split("\t")[3])
ValueError: could not convert string to float: 'Valence'
```

To reproduce in Docker:

```
docker run --interactive --tty ubuntu:18.04 bash
apt update; apt install -y git nano wget htop python3 python3-pip unzip; git clone https://github.com/RiTUAL-UH/Font_LDL_2020; cd Font_LDL_2020; pip3 install -r requirements.txt; cd Font_LDL
python3 -m nltk.downloader wordnet

mkdir -p DATA/font
git clone https://github.com/RiTUAL-UH/Font-prediction-dataset
cp -r Font-prediction-dataset/DATA/* DATA/font

mkdir -p DATA/emotion_lexicon
wget http://sentiment.nrc.ca/lexicons-for-research/NRC-Sentiment-Emotion-Lexicons.zip
unzip NRC-Sentiment-Emotion-Lexicons.zip
cp -r NRC-Sentiment-Emotion-Lexicons/NRC-Emotion-Lexicon-v0.92/* DATA/emotion_lexicon
cp -r NRC-Sentiment-Emotion-Lexicons/NRC-VAD-Lexicon/* DATA/emotion_lexicon

mkdir -p EMBEDDINGS/glove.6B
wget http://nlp.stanford.edu/data/glove.6B.zip
unzip glove.6B.zip -d EMBEDDINGS/glove.6B

PYTHONIOENCODING=utf8 python3 main.py
```

**Comment by Franck-Dernoncourt** [comment]
The error  has changed for some reasons, even though I use the same Docker command in the message above.

New error message:

```
root@b4c1dede07bb:/Font_LDL_2020/Font_LDL# PYTHONIOENCODING=utf8 python3 main.py
[LOG] running on CPU
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from data import Corpus, Encoder
  File "/Font_LDL_2020/Font_LDL/data.py", line 10, in <module>
    tokenizer = spacy.load("en_core_web_sm")
  File "/usr/local/lib/python3.6/dist-packages/spacy/__init__.py", line 18, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 135, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/lib/python3.6/dist-packages/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 636, in <lambda>
    ('tokenizer', lambda p: self.tokenizer.from_disk(p, vocab=False)),
  File "tokenizer.pyx", line 367, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 402, in spacy.tokenizer.Tokenizer.from_bytes
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 490, in from_bytes
    msg = msgpack.loads(bytes_data, raw=False)
  File "/usr/local/lib/python3.6/dist-packages/msgpack_numpy.py", line 183, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: int is not allowed for map key
root@b4c1dede07bb:/Font_LDL_2020/Font_LDL#
```
